Implemented page profile
Max2002/contact-api pull request #5
Opened 2022-10-11 15:56 UTC by Max2002

2022-10-12 12:08 UTC, GCoder-13 commented on src/App.js
> +import Profile from './sections/Profile/index';
./sections/Profile

2022-10-12 12:10 UTC, GCoder-13 commented on src/assets/styles/variables.scss
> +$error404: 80px;
Use variable font sizes only where they can be repeated

2022-10-12 12:19 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +import { CopyToClipboard } from 'react-copy-to-clipboard';
dont use libs

2022-10-12 12:19 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +      {isLink ? (
???

2022-10-12 12:21 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +export default function CopyElement({ children, isLink, prefixLink }) {
Don’t use children for string

2022-10-12 12:22 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +      {renderPrefix()}
???

2022-10-12 12:24 UTC, GCoder-13 commented on src/components/CopyElement/styles.module.scss
> +  a {
???

2022-10-12 12:26 UTC, GCoder-13 commented on src/sections/Profile/index.js
> +  const renderElement = (element, flag, width = 375, height = 15) => {
create component

2022-10-12 12:26 UTC, GCoder-13 commented on src/sections/Profile/styles.module.scss
> +.personalInfo {
????

2022-10-13 12:25 UTC, Max2002 commented on src/components/CopyElement/index.js
> +      {isLink ? (
incorrect name variable

2022-10-13 12:31 UTC, Max2002 commented on src/components/CopyElement/styles.module.scss
> +  a {
don't access the selector directly

2022-10-14 07:10 UTC, Max2002 commented on src/sections/Profile/styles.module.scss
> +.personalInfo {
empty css class

2022-10-14 09:57 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +    const interval = setInterval(() => setIsCopied(false), 2000);
Infinity interval

2022-10-14 09:58 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +          <CopySvg onClick={() => handleCopy(content)} />
???

2022-10-14 09:58 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +        <a className={st.link} href={`${prefixLink}${content}`}>
href

2022-10-14 09:59 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +  link: PropTypes.bool,
incorect type

2022-10-14 09:59 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +  prefixLink: PropTypes.string,
delete

2022-10-14 09:59 UTC, GCoder-13 commented on src/components/CopyElement/styles.module.scss
> +  svg {
???

2022-10-14 10:00 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +      <div className={st.icon}>
rename

2022-10-14 10:01 UTC, GCoder-13 commented on src/components/LoadingElement/index.js
> +  return flag ? (
rename flag

2022-10-14 10:01 UTC, GCoder-13 commented on src/components/LoadingElement/index.js
> +    element
???

2022-10-14 10:04 UTC, GCoder-13 commented on src/sections/Profile/index.js
> +    <div className={`container ${st.profile}`}>
container must be component

2022-10-14 10:05 UTC, GCoder-13 commented on src/sections/Profile/styles.module.scss
> +  span {
???

2022-10-14 10:49 UTC, Max2002 commented on src/components/CopyElement/index.js
> +          <CopySvg onClick={() => handleCopy(content)} />
it is neccessary, because value in variable content

2022-10-14 11:19 UTC, Max2002 commented on src/components/CopyElement/styles.module.scss
> +  svg {
use css class

2022-10-14 11:19 UTC, Max2002 commented on src/sections/Profile/styles.module.scss
> +  span {
use css class

2022-10-17 08:12 UTC, GCoder-13 commented on src/components/CopyElement/styles.module.scss
> +.copy, .copied {
use 1 class

2022-10-17 08:15 UTC, GCoder-13 commented on src/sections/Profile/index.js
> +      <div className={st.profile}>
unnecessary wrapper

2022-10-17 18:33 UTC, GCoder-13 commented on src/components/Container/index.js
> +  className: PropTypes.string.isRequired,
Not required

2022-10-17 18:34 UTC, GCoder-13 commented on src/components/CopyElement/index.js
> +          <CopiedSvg className={`${st.copiesSvg} ${st.copied}`} />
Clsx

2022-10-17 18:36 UTC, GCoder-13 commented on src/components/CopyElement/styles.module.scss
> +    border: 7px solid transparent;
Why?

2022-10-17 18:38 UTC, GCoder-13 commented on src/components/Menu/index.js
> +      <LoadingElement loading={!loading} width={200}>
Loading?

2022-10-19 18:59 UTC, GCoder-13 commented on src/components/CopyElement/styles.module.scss
> +  //margin-right: 10px;
delete

2022-10-19 19:01 UTC, GCoder-13 commented on src/components/Menu/index.js
>        <div className={st.dropDownList}>
do you really need this container?

2022-10-19 19:02 UTC, GCoder-13 commented on src/components/Menu/index.js
> +  avatar: PropTypes.string,
avatarUrl

2022-10-19 19:04 UTC, GCoder-13 commented on src/sections/Profile/index.js
> +        <div>
do you really need this container?

2022-10-19 19:05 UTC, GCoder-13 commented on src/sections/Profile/styles.module.scss
> +  font-size: 80%;
don't use percent for font-size. Only px or rem

2022-10-20 06:27 UTC, Max2002 commented on src/components/Menu/index.js
>        <div className={st.dropDownList}>
no

2022-10-20 06:33 UTC, Max2002 commented on src/sections/Profile/index.js
> +        <div>
yes, because without this doesn`t work flex

2022-10-20 21:51 UTC, GCoder-13 requested changes

2022-10-20 21:51 UTC, GCoder-13 commented on src/components/Hint/index.js
> +export default function Hint({ children, className }) {
hover effect must be implemented inside this component

2022-10-21 10:28 UTC, GCoder-13 approved these changes

2022-10-21 10:33 UTC, merged